// Generates src/props.ts from design/jasno.elements.d.ts: the closed prop names per tag (UNKNOWN_PROP, B15.8)
// and the message-typed keys with their hints. Run: node tools/gen-props.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const src = readFileSync(new URL('../../design/jasno.elements.d.ts', import.meta.url), 'utf8');
const ifaces = new Map();
for (const m of src.matchAll(/export interface (\w+)(?:<[^>]*>)?(?: extends (\w+)<[^>]*>)? \{(?:\}|([\s\S]*?)\n  \})/g)) {
  const keys = [...(m[3] ?? '').matchAll(/^\s+'?([A-Za-z][\w-]*)'?\?:\s*(.*)$/gm)].map((k) => [k[1], k[2]]);
  ifaces.set(m[1], { base: m[2], keys });
}
const forbidden = {};
const allKeys = (name) => {
  const i = ifaces.get(name);
  if (!i) return [];
  return [...allKeys(i.base), ...i.keys.map(([k, t]) => {
    const msg = /"jasno: ([^"]+)"/.exec(t);
    if (msg) forbidden[k] = msg[1];
    return msg ? null : k;
  }).filter(Boolean)];
};
const global = new Set(allKeys('GlobalProps').filter((k) => !k.startsWith('on')));
const perTag = {};
for (const m of src.matchAll(/^    (\w+): \(props: (\w+) \| null/gm)) {
  perTag[m[1]] = allKeys(m[2]).filter((k) => !k.startsWith('on') && !global.has(k));
}
const out = `// Generated by tools/gen-props.mjs from design/jasno.elements.d.ts. Do not edit.
export const GLOBAL_PROPS: ReadonlySet<string> = new Set(${JSON.stringify([...global])});
export const TAG_PROPS: Readonly<Record<string, readonly string[]>> = ${JSON.stringify(perTag)};
export const FORBIDDEN_PROPS: Readonly<Record<string, string>> = ${JSON.stringify(forbidden)};
`;
writeFileSync(new URL('../src/props.ts', import.meta.url), out);
console.log(`props.ts: ${global.size} global, ${Object.keys(perTag).length} tags, ${Object.keys(forbidden).length} forbidden`);
